name: CI/CD to Staging

env:
  RE_CAPTCHA_ENTERPRISE_SITE_KEY: ${{ secrets.RE_CAPTCHA_ENTERPRISE_SITE_KEY }}

on: pull_request

jobs:
  Deploy_Staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Verify code format
        run: npm run format-check

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
