name: CI/CD to Production

env:
  RE_CAPTCHA_ENTERPRISE_SITE_KEY: ${{ secrets.RE_CAPTCHA_ENTERPRISE_SITE_KEY }}

on:
  push:
    branches:
      - master

jobs:
  Deploy_Production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Verify code format
        run: npm run format-check

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
